/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LED.h>
#include <LED_aliases.h>
#include <Button.h>
#include <Button_aliases.h>
#include <RGBLed.h>
#include <RGBLed_aliases.h>
#include <Rx_Front.h>
#include <Rx_Right.h>
#include <Rx_Right_SPI_UART.h>
#include <Rx_Right_PINS.h>
#include <Rx_Right_SPI_UART_PVT.h>
#include <Rx_Right_PVT.h>
#include <Rx_Right_BOOT.h>
#include <isr_Rx_Front.h>
#include <Rx_Left.h>
#include <Rx_Left_SPI_UART.h>
#include <Rx_Left_PINS.h>
#include <Rx_Left_SPI_UART_PVT.h>
#include <Rx_Left_PVT.h>
#include <Rx_Left_BOOT.h>
#include <Rx_Front_Pins.h>
#include <Rx_Front_Pins_aliases.h>
#include <Rx_Back.h>
#include <Rx_Back_Pins.h>
#include <Rx_Back_Pins_aliases.h>
#include <isr_Rx_Back.h>
#include <Rx_Front_IntClock.h>
#include <Rx_Right_SCBCLK.h>
#include <Rx_Right_tx.h>
#include <Rx_Right_tx_aliases.h>
#include <Rx_Right_SCB_IRQ.h>
#include <Rx_Right_rx.h>
#include <Rx_Right_rx_aliases.h>
#include <Rx_Left_SCBCLK.h>
#include <Rx_Left_SCB_IRQ.h>
#include <Rx_Left_rx.h>
#include <Rx_Left_rx_aliases.h>
#include <Rx_Back_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

