/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Tx.h>
#include <Rx_Right.h>
#include <isr_Rx_Left.h>
#include <Rx_Left_Pins_aliases.h>
#include <Rx_Left_Pins.h>
#include <Rx_Front.h>
#include <Rx_Left.h>
#include <isr_Rx_Back.h>
#include <Rx_Back.h>
#include <isr_Rx_Front.h>
#include <Rx_Back_Pins_aliases.h>
#include <Rx_Back_Pins.h>
#include <LCD.h>
#include <Rx_Front_Pins_aliases.h>
#include <Rx_Front_Pins.h>
#include <Rx_Right_Pins_aliases.h>
#include <Rx_Right_Pins.h>
#include <isr_Rx_Right.h>
#include <LED_aliases.h>
#include <LED.h>
#include <Button_aliases.h>
#include <Button.h>
#include <StartupLED_aliases.h>
#include <StartupLED.h>
#include <Rx_Front_Register.h>
#include <Clock_1.h>
#include <Rx_Back_Register.h>
#include <Rx_Top.h>
#include <Rx_Left_Register.h>
#include <Rx_Right_Register.h>
#include <Rx_Top_Pins_aliases.h>
#include <Rx_Top_Pins.h>
#include <isr_Rx_Top.h>
#include <Rx_Top_Register.h>
#include <Rx_Bottom.h>
#include <Rx_Bottom_Pins_aliases.h>
#include <Rx_Bottom_Pins.h>
#include <isr_Rx_Bottom.h>
#include <Rx_Bottom_Register.h>
#include <Tx_IntClock.h>
#include <Rx_Right_IntClock.h>
#include <Rx_Front_IntClock.h>
#include <Rx_Left_IntClock.h>
#include <Rx_Back_IntClock.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <Rx_Top_IntClock.h>
#include <Rx_Bottom_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

